### ISSUE TITLE
android cross-build needs the extension module to be linked against the math library

### ISSUE THREAD

**Issue by xdegaye** [brandon-rhodes/pyephem#114]
The patch in CPython [issue 28833: cross compilation of third-party extension modules](http://bugs.python.org/issue28833) has been tested with pyephem and the following patch to pyephem had to be applied in order to have it run on an Android emulator:
```
--- ephem-3.7.6.0/setup.py      2015-08-19 06:43:55.000000000 +0200
+++ extension_module/ephem-3.7.6.0/setup.py     2016-11-27 20:36:21.375268171 +0100
@@ -24,6 +24,7 @@
               ['extensions/_libastro.c', 'extensions/dtoa.c']
               + libastro_files + libastro_data,
               include_dirs=['libastro-' + libastro_version],
+              libraries = ['m'],
               ),
     ]
```

Without the patch, the following error occurs on Android API level 21:
```
root@generic_x86:/data/data/org.bitbucket.pyona # python
Python 3.7.0a0 (default:876bee0bd0ba+, Nov 29 2016, 15:36:23)
[GCC 4.2.1 Compatible Android Clang 3.8.256229 ] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ephem
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/org.bitbucket.pyona/python/lib/python3.7/site-packages/ephem/__init__.py", line 5, in <module>
    import ephem._libastro as _libastro
ImportError: dlopen failed: cannot locate symbol "fmod" referenced by "_libastro.cpython-37dm-i686-linux-android.so"...
```

**Comment by brandon-rhodes** [comment]
Thanks! I will plan on putting this change in the next version of PyEphem.
