### ISSUE TITLE
Garbage in README.rst, patch included

### ISSUE THREAD

**Issue by JeffRossMT** [brandon-rhodes/pyephem#182]
```
root:4181# pip3 install ephem
Collecting ephem
  Downloading ephem-3.7.7.1.tar.gz (745 kB)
     |################################| 745 kB 3.5 MB/s
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rl6jf7o4/ephem/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rl6jf7o4/ephem/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-1r6pr1o2
         cwd: /tmp/pip-install-rl6jf7o4/ephem/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-rl6jf7o4/ephem/setup.py", line 40, in <module>
        long_description = read('README.rst'),
      File "/tmp/pip-install-rl6jf7o4/ephem/setup.py", line 27, in read
        return open(os.path.join(os.path.dirname(__file__), *filenames)).read()
      File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4461: ordinal not in range(128)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
root:4182# cd /tmp/
root:4183# wget https://github.com/brandon-rhodes/pyephem/archive/master.zip
--2020-11-27 09:02:55--  https://github.com/brandon-rhodes/pyephem/archive/master.zip
Resolving github.com (github.com)... 140.82.112.4
Connecting to github.com (github.com)|140.82.112.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/brandon-rhodes/pyephem/zip/master [following]
--2020-11-27 09:02:56--  https://codeload.github.com/brandon-rhodes/pyephem/zip/master
Resolving codeload.github.com (codeload.github.com)... 140.82.112.9
Connecting to codeload.github.com (codeload.github.com)|140.82.112.9|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: 'master.zip'
root:4184# unzip master.zip
root:4185# cd pyephem-master
root:4188# python3 setup.py
Traceback (most recent call last):
  File "setup.py", line 40, in <module>
    long_description = read('README.rst'),
  File "setup.py", line 27, in read
    return open(os.path.join(os.path.dirname(__file__), *filenames)).read()
  File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4461: ordinal not in range(128)
```
Patch to fix:
```
root:4204# cd pyephem-master/
root:4205# cp README.rst README.rst.orig
root:4206# nano README.rst
root:4207# diff -u3 README.rst.orig README.rst
--- README.rst.orig     Fri Nov 27 09:10:44 2020
+++ README.rst  Fri Nov 27 09:11:16 2020
@@ -120,13 +120,13 @@

     python -m unittest discover ephem

-PyEphem’s documentation is organized as a standard `Sphinx
+PyEphem's documentation is organized as a standard `Sphinx
 <http://www.sphinx-doc.org/en/master/>`_ document project.  You can
 build the documentation either with the Sphinx command line::

     sphinx-build -b html pyephem/ephem/doc/ ./my_documentation_directory/

-— or, more typically, by invoking one of the targets in the
-documentation’s Makefile::
+-- or, more typically, by invoking one of the targets in the
+documentation's Makefile::

     make -C ephem/doc html
```

python3 setup.py install now successfully installs epehm.

**Comment by brandon-rhodes** [comment]
Interesting, it must rely on the system encoding, instead of forcing its own. Could you edit `setup.py` and provide this function instead and see if it fixes the problem?
```
def read(*filenames):
    path = os.path.join(os.path.dirname(__file__), *filenames)
    return open(path, 'rb').read().decode('utf-8')
```
Thanks!

**Comment by JeffRossMT** [comment]
That fix also works.
