### ISSUE TITLE
MacOS 11.0 "Big Sur" - pip3 pyephem and ephem installs fail

### ISSUE THREAD

**Issue by chrisale** [brandon-rhodes/pyephem#183]
Unfortunately pip3 ephem and pip3 pyephem fail to build and install on the newly upgraded system.

The error is:
AttributeError: 'int' object has no attribute 'split'

Below is the error output when running.

Cheers
Chris
```
  ERROR: Failed building wheel for ephem
  Running setup.py clean for ephem
Successfully built pyephem
Failed to build ephem
Installing collected packages: ephem, pyephem
    Running setup.py install for ephem ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/sp/g3bd7ndd2f3bstytj5qv8c8c0000gn/T/pip-install-lri397ea/ephem_f26b51ebaa6145eb826a19b41f1dda89/setup.py'"'"'; __file__='"'"'/private/var/folders/sp/g3bd7ndd2f3bstytj5qv8c8c0000gn/T/pip-install-lri397ea/ephem_f26b51ebaa6145eb826a19b41f1dda89/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/sp/g3bd7ndd2f3bstytj5qv8c8c0000gn/T/pip-record-nc_tqcuj/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/ephem
         cwd: /private/var/folders/sp/g3bd7ndd2f3bstytj5qv8c8c0000gn/T/pip-install-lri397ea/ephem_f26b51ebaa6145eb826a19b41f1dda89/
    Complete output (119 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-11-x86_64-3.9
    creating build/lib.macosx-11-x86_64-3.9/ephem
    copying ephem/__init__.py -> build/lib.macosx-11-x86_64-3.9/ephem
    copying ephem/stars.py -> build/lib.macosx-11-x86_64-3.9/ephem
    copying ephem/cities.py -> build/lib.macosx-11-x86_64-3.9/ephem
    creating build/lib.macosx-11-x86_64-3.9/ephem/tests
    copying ephem/tests/test_usno_equinoxes.py -> build/lib.macosx-11-x86_64-3.9/ephem/tests
    copying ephem/tests/test_stars.py -> build/lib.macosx-11-x86_64-3.9/ephem/tests
    copying ephem/tests/test_cities.py -> build/lib.macosx-11-x86_64-3.9/ephem/tests
    copying ephem/tests/test_dates.py -> build/lib.macosx-11-x86_64-3.9/ephem/tests
    copying ephem/tests/test_launchpad_244811.py -> build/lib.macosx-11-x86_64-3.9/ephem/tests
    copying ephem/tests/__init__.py -> build/lib.macosx-11-x86_64-3.9/ephem/tests
    copying ephem/tests/test_observers.py -> build/lib.macosx-11-x86_64-3.9/ephem/tests
    copying ephem/tests/test_launchpad_236872.py -> build/lib.macosx-11-x86_64-3.9/ephem/tests
    copying ephem/tests/test_jpl.py -> build/lib.macosx-11-x86_64-3.9/ephem/tests
    copying ephem/tests/test_locales.py -> build/lib.macosx-11-x86_64-3.9/ephem/tests
    copying ephem/tests/test_rst.py -> build/lib.macosx-11-x86_64-3.9/ephem/tests
    copying ephem/tests/test_github_issues.py -> build/lib.macosx-11-x86_64-3.9/ephem/tests
    copying ephem/tests/test_usno.py -> build/lib.macosx-11-x86_64-3.9/ephem/tests
    copying ephem/tests/test_bodies.py -> build/lib.macosx-11-x86_64-3.9/ephem/tests
    copying ephem/tests/test_constants.py -> build/lib.macosx-11-x86_64-3.9/ephem/tests
    copying ephem/tests/test_satellite.py -> build/lib.macosx-11-x86_64-3.9/ephem/tests
    copying ephem/tests/test_angles.py -> build/lib.macosx-11-x86_64-3.9/ephem/tests
    creating build/lib.macosx-11-x86_64-3.9/ephem/doc
    copying ephem/doc/angle.rst -> build/lib.macosx-11-x86_64-3.9/ephem/doc
    copying ephem/doc/index.rst -> build/lib.macosx-11-x86_64-3.9/ephem/doc
    copying ephem/doc/reference.rst -> build/lib.macosx-11-x86_64-3.9/ephem/doc
    copying ephem/doc/tutorial.rst -> build/lib.macosx-11-x86_64-3.9/ephem/doc
    copying ephem/doc/examples.rst -> build/lib.macosx-11-x86_64-3.9/ephem/doc
    copying ephem/doc/coordinates.rst -> build/lib.macosx-11-x86_64-3.9/ephem/doc
    copying ephem/doc/quick.rst -> build/lib.macosx-11-x86_64-3.9/ephem/doc
    copying ephem/doc/rise-set.rst -> build/lib.macosx-11-x86_64-3.9/ephem/doc
    copying ephem/doc/date.rst -> build/lib.macosx-11-x86_64-3.9/ephem/doc
    copying ephem/doc/CHANGELOG.rst -> build/lib.macosx-11-x86_64-3.9/ephem/doc
    copying ephem/doc/radec.rst -> build/lib.macosx-11-x86_64-3.9/ephem/doc
    copying ephem/doc/newton.rst -> build/lib.macosx-11-x86_64-3.9/ephem/doc
    copying ephem/doc/catalogs.rst -> build/lib.macosx-11-x86_64-3.9/ephem/doc
    creating build/lib.macosx-11-x86_64-3.9/ephem/tests/jpl
    copying ephem/tests/jpl/phobos.txt -> build/lib.macosx-11-x86_64-3.9/ephem/tests/jpl
    copying ephem/tests/jpl/europa.txt -> build/lib.macosx-11-x86_64-3.9/ephem/tests/jpl
    copying ephem/tests/jpl/uranus.txt -> build/lib.macosx-11-x86_64-3.9/ephem/tests/jpl
    copying ephem/tests/jpl/jupiter.txt -> build/lib.macosx-11-x86_64-3.9/ephem/tests/jpl
    copying ephem/tests/jpl/hyperion.txt -> build/lib.macosx-11-x86_64-3.9/ephem/tests/jpl
    copying ephem/tests/jpl/oberon.txt -> build/lib.macosx-11-x86_64-3.9/ephem/tests/jpl
    copying ephem/tests/jpl/mars.txt -> build/lib.macosx-11-x86_64-3.9/ephem/tests/jpl
    copying ephem/tests/jpl/saturn.txt -> build/lib.macosx-11-x86_64-3.9/ephem/tests/jpl
    copying ephem/tests/jpl/neptune.txt -> build/lib.macosx-11-x86_64-3.9/ephem/tests/jpl
    creating build/lib.macosx-11-x86_64-3.9/ephem/tests/usno
    copying ephem/tests/usno/apptopo_deneb.txt -> build/lib.macosx-11-x86_64-3.9/ephem/tests/usno
    copying ephem/tests/usno/astrom_mercury.txt -> build/lib.macosx-11-x86_64-3.9/ephem/tests/usno
    copying ephem/tests/usno/appgeo_deneb.txt -> build/lib.macosx-11-x86_64-3.9/ephem/tests/usno
    copying ephem/tests/usno/apptopo_moon.txt -> build/lib.macosx-11-x86_64-3.9/ephem/tests/usno
    copying ephem/tests/usno/risettran_rigel.txt -> build/lib.macosx-11-x86_64-3.9/ephem/tests/usno
    copying ephem/tests/usno/risettran_moon.txt -> build/lib.macosx-11-x86_64-3.9/ephem/tests/usno
    copying ephem/tests/usno/astrom_neptune.txt -> build/lib.macosx-11-x86_64-3.9/ephem/tests/usno
    copying ephem/tests/usno/riset_sun.txt -> build/lib.macosx-11-x86_64-3.9/ephem/tests/usno
    copying ephem/tests/usno/apptopo_sun.txt -> build/lib.macosx-11-x86_64-3.9/ephem/tests/usno
    copying ephem/tests/usno/appgeo_moon.txt -> build/lib.macosx-11-x86_64-3.9/ephem/tests/usno
    copying ephem/tests/usno/appgeo_jupiter.txt -> build/lib.macosx-11-x86_64-3.9/ephem/tests/usno
    copying ephem/tests/usno/astrom_antares.txt -> build/lib.macosx-11-x86_64-3.9/ephem/tests/usno
    copying ephem/tests/usno/moon_phases.txt -> build/lib.macosx-11-x86_64-3.9/ephem/tests/usno
    copying ephem/tests/usno/riset_moon.txt -> build/lib.macosx-11-x86_64-3.9/ephem/tests/usno
    copying ephem/tests/usno/appgeo_sun.txt -> build/lib.macosx-11-x86_64-3.9/ephem/tests/usno
    running build_ext
    building 'ephem._libastro' extension
    creating build/temp.macosx-11-x86_64-3.9
    creating build/temp.macosx-11-x86_64-3.9/extensions
    creating build/temp.macosx-11-x86_64-3.9/extensions/data
    creating build/temp.macosx-11-x86_64-3.9/libastro-3.7.7
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -Ilibastro-3.7.7 -I. -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c extensions/_libastro.c -o build/temp.macosx-11-x86_64-3.9/extensions/_libastro.o
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/sp/g3bd7ndd2f3bstytj5qv8c8c0000gn/T/pip-install-lri397ea/ephem_f26b51ebaa6145eb826a19b41f1dda89/setup.py", line 37, in <module>
        setup(name = 'ephem',
      File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.9/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/install.py", line 546, in run
        self.run_command('build')
      File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/usr/local/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build_ext.py", line 529, in build_extension
        objects = self.compiler.compile(sources,
      File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/unixccompiler.py", line 117, in _compile
        self.spawn(compiler_so + cc_args + [src, '-o', obj] +
      File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/ccompiler.py", line 910, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/spawn.py", line 66, in spawn
        if _cfg_target_split > [int(x) for x in cur_target.split('.')]:
    AttributeError: 'int' object has no attribute 'split'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/opt/python@3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/sp/g3bd7ndd2f3bstytj5qv8c8c0000gn/T/pip-install-lri397ea/ephem_f26b51ebaa6145eb826a19b41f1dda89/setup.py'"'"'; __file__='"'"'/private/var/folders/sp/g3bd7ndd2f3bstytj5qv8c8c0000gn/T/pip-install-lri397ea/ephem_f26b51ebaa6145eb826a19b41f1dda89/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/sp/g3bd7ndd2f3bstytj5qv8c8c0000gn/T/pip-record-nc_tqcuj/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/ephem Check the logs for full command output.
```

**Comment by brandon-rhodes** [comment]
Thanks for the report! (I just edited your text to put triple-backticks around the error text; hopefully you'll find that it makes it easier for us to read.)

I have never seen that error before myself, but these issues come up from a Google search:

https://github.com/Homebrew/homebrew-core/issues/66096

https://github.com/Homebrew/brew/issues/9329

Do either of those issues suggest a workaround that might get you going again?

**Comment by brandon-rhodes** [comment]
As it’s been nearly a year without any further update, I'm going to go ahead and close this issue in the hopes that it was resolved by the links I shared (or, otherwise, by some other fortunate fix).
