### ISSUE TITLE
"pip install" of 3.7.5.3 fails (error: must supply either home or prefix/exec-prefix -- not both)

### ISSUE THREAD

**Issue by dstndstn** [brandon-rhodes/pyephem#70]
Hi,
On my MacOS X box,

```
> pip install -v ephem
Downloading/unpacking ephem
  Using version 3.7.5.3 (newest of versions: 3.7.5.3, 3.7.5.1, 3.7.3.4, 3.7.3.3)
  Downloading ephem-3.7.5.3.tar.gz (735kB):
  Downloading from URL https://pypi.python.org/packages/source/e/ephem/ephem-3.7.5.3.tar.gz#md5=0e33905844e3be5c901c13e5a9c938a3 (from https://pypi.python.org/simple/ephem/)
...Downloading ephem-3.7.5.3.tar.gz (735kB): 735kB downloaded
  Running setup.py (path:/private/var/folders/vp/tcndx7bn5szg0v7rbzd1k8nm0000gn/T/pip_build_dstn/ephem/setup.py) egg_info for package ephem
    running egg_info
    creating pip-egg-info/ephem.egg-info
    writing pip-egg-info/ephem.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/ephem.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/ephem.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/ephem.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'pip-egg-info/ephem.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/ephem.egg-info/SOURCES.txt'
Installing collected packages: ephem
  Running setup.py install for ephem
    running install
    error: must supply either home or prefix/exec-prefix -- not both
    Complete output from command /usr/local/opt/python/bin/python2.7 -c "import setuptools, tokenize;__file__='/private/var/folders/vp/tcndx7bn5szg0v7rbzd1k8nm0000gn/T/pip_build_dstn/ephem/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/vp/tcndx7bn5szg0v7rbzd1k8nm0000gn/T/pip-Tzpl_x-record/install-record.txt --single-version-externally-managed --compile --home=/usr/local/pipped:
    running install

error: must supply either home or prefix/exec-prefix -- not both

----------------------------------------
Cleaning up...
  Removing temporary dir /private/var/folders/vp/tcndx7bn5szg0v7rbzd1k8nm0000gn/T/pip_build_dstn...
Command /usr/local/opt/python/bin/python2.7 -c "import setuptools, tokenize;__file__='/private/var/folders/vp/tcndx7bn5szg0v7rbzd1k8nm0000gn/T/pip_build_dstn/ephem/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/vp/tcndx7bn5szg0v7rbzd1k8nm0000gn/T/pip-Tzpl_x-record/install-record.txt --single-version-externally-managed --compile --home=/usr/local/pipped failed with error code 1 in /private/var/folders/vp/tcndx7bn5szg0v7rbzd1k8nm0000gn/T/pip_build_dstn/ephem
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/local/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/req.py", line 1435, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/req.py", line 706, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/usr/local/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command /usr/local/opt/python/bin/python2.7 -c "import setuptools, tokenize;__file__='/private/var/folders/vp/tcndx7bn5szg0v7rbzd1k8nm0000gn/T/pip_build_dstn/ephem/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/vp/tcndx7bn5szg0v7rbzd1k8nm0000gn/T/pip-Tzpl_x-record/install-record.txt --single-version-externally-managed --compile --home=/usr/local/pipped failed with error code 1 in /private/var/folders/vp/tcndx7bn5szg0v7rbzd1k8nm0000gn/T/pip_build_dstn/ephem

Storing debug log for failure in /Users/dstn/.pip/pip.log
```

I also notice that the "gittib" build is failing, according to the badge here:
https://pypi.python.org/pypi/ephem/3.7.5.3

Happy solstice season,
--dustin

**Comment by danielwhatmuff** [comment]
The workaround breaks other pip stuff... 👎

**Comment by ai-nikolai** [comment]
**I had this issue again (in 2020).** 

If you are still having this issue, I only had to:
1. upgrade to pip 20.3.1  from 18 (smthg) `sudo python3 -m pip install --upgrade pip`



System setup overall:
- Python 3.6.5
- Homebrew 2.1.7
